language: java

git: 
  quiet: false

before_install:
  - gradle installWrapper

jobs:
  allow_failures:
  - os: osx
  include:
  - jdk: openjdk11
    os: linux
  - jdk: openjdk11
    os: osx


notifications:
  email:
    recipients:
    - sophieheinz@magenta.de
  on_success: always
  on_failure: always

script: ./gradlew buildCore
